# Generated by Django 5.2.11 on 2026-02-07 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=10)),
                ('weight', models.CharField(blank=True, max_length=10)),
                ('bmi', models.CharField(blank=True, max_length=10)),
                ('fruit_veg_intake', models.CharField(blank=True, max_length=50)),
                ('processed_food_intake', models.CharField(blank=True, max_length=50)),
                ('dietary_habits', models.TextField(blank=True)),
                ('physical_activity_level', models.CharField(blank=True, max_length=50)),
                ('average_sleep_time', models.CharField(blank=True, max_length=50)),
                ('smoking_habit', models.CharField(blank=True, max_length=50)),
                ('alcohol_consumption', models.CharField(blank=True, max_length=50)),
                ('symptoms', models.TextField(blank=True)),
                ('risk_level', models.CharField(blank=True, max_length=50)),
                ('risk_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
