# Generated by Django 5.2.11 on 2026-02-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
