# Generated by Django 5.2.11 on 2026-02-10 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_assessment_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='medical_history',
            field=models.TextField(blank=True),
        ),
    ]
